src/main/filtered-resources/etc/custom.properties

[BACKLOG-312] - taking advantage of the wildcard support added for kettle steps

[BACKLOG-312] - taking advantage of the wildcard support added for kettle steps

---

pentaho-blueprint-activators/pom.xml
pentaho-karaf-features/pom.xml
pentaho-osgi-config/pom.xml
pom.xml

@lgrill-pentaho @CodeOnCoffee   for review.  See execution at http://cerberus.pentaho.com/job/futurama-nightly/job/karaf-ce-assembly/104/

[CLEANUP] refactored poms to use ce-parent-pom

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
src/main/filtered-resources/etc/custom.properties

Add PDI Dataservice client bundle to pentaho-client
Should be pulled after pentaho/pentaho-kettle#1071 to avoid duplication

[BACKLOG-411]Add Data Service JDBC client to assembly

---

src/main/filtered-resources/etc/custom.properties

[BACKLOG-3255] Cleanup some interactions with the Data Services

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-3775] Make Data Services CE

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

[BACKLOG-3857]Add packages for embedded metastore

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml

OSGi race condition loading bundles
@brendan-lynch @bmorrise

[CLEANUP]Update pdi-dataservice dependency

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Reverts pentaho/pentaho-karaf-assembly#92

Revert "[CLEANUP] - Commenting out the Big Data dependency"

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-3775] Make Dataservices CE

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg

[CLEANUP] fix pdi-dataservice feature name

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml

[CLEANUP] added obf features for monitoring

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/mondrian.cfg

This commit brings mondrian.cfg under karaf's /etc.  Formerly
hadn't been moved from it's old location osgi/bundles.
@kurtwalker

[BACKLOG-4922]   Upgrading to vfs2.1

---

pentaho-karaf-features/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml

[CLEANUP] obf related parameterization for mongolap and monitoring

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

[BACKLOG-5130] [DataServices] Error installing plugin "pdi-dataservice-server-plugin" on pdi-ee start-up

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties

@rfellows Mind a review/merge?
@pentaho-nbaker @deinspanjer FYI

[BACKLOG-5070] Add new TextFileInput step packages to custom.properties

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-prd/org.apache.karaf.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Created a pdi-dataservice client feature

 [BACKLOG-5229] - Adding pdi-dataservice client feature to prd

---

pentaho-osgi-config/src/main/resources/pentaho.metaverse.cfg

@rfellows Please and thanks! pentaho-metaverse PR to come.

[BACKLOG-5308] Add property to lineage config to disable runtime collection by default

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg

@pentaho-nbaker for your review

[BACKLOG-5317] Remove YARN from CE features

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

[BISERVER-12915] - Package import fixes resulting from the recent wildcard support changes

[BISERVER-12915] - Package import fixes resulting from the recent wildcard support changes

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pentaho-osgi-config/pom.xml
pentaho-osgi-config/src/main/resources/pentaho.geo.roles.cfg

[BACKLOG-5653] - pdi-data-refinery converted from legacy plugin to maven bundle and feature

[BACKLOG-5653] - pdi-data-refinery converted from legacy plugin to maven bundle and feature

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-5695] - Including the data-refinery feature/bundle in the karaf assembly

[BACKLOG-5695] - Including the data-refinery feature/bundle in the karaf assembly

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-pmr/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-prd/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml

- [CHERRY-PICK] https://github.com/SergeyTravin/pentaho-karaf-assembly/commit/73dada0934c471b57da4d90ca80228a4eb2d61d1

[SP-2227][PPP-3448] Apache CXF 3.0.6 Vulnerability w/SAML

---

pentaho-karaf-features/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

- Updated pentaho angular bundle version property

[BACKLOG-6318] - Added common-ui as a dependency of pdi-marketplace feature.

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Needs to be merged with this: https://github.com/pentaho/pentaho-metaverse/pull/406

[PDI-14690] Split web components into separate feature

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties

Adding dependencies and pdi-data-refinery feature to install at carte startup

BACKLOG-6794 - Unable to run model on diserver

---

pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc/config.properties

If it's not set, it will try to write config.properties on startup (see http://karaf.922171.n3.nabble.com/Karaf-3-0-2-tries-to-write-to-etc-config-properties-terminates-on-failure-td4037973.html)

[PDI-15058] - Setting shutdown command

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-7661] Added repositories-plugin to the assembly

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

[BACKLOG-7463] Added simple json to custom.properties

---

pentaho-karaf-assembly/pom.xml
pom.xml

* Changed version of the mongo driver  to 3.2.2
* Removed dublicate property from child pom

[BACKLOG-7093] - Upgrade Mongo version to latest (3.2)

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

…oducts (Add to Feature)
- Bundle versions fix

[BACKLOG-8624] - Make Localization Service available by default in products (Add to Feature). Bundle version fix.

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Reverts pentaho/pentaho-karaf-assembly#204

Revert "[BACKLOG-9100] Pluginize the Metadata Injection step"

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-9100] Pluginize the Metadata Injection step

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/startup.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

_*merge following* https://github.com/pentaho/pentaho-det-ee/pull/153_

[BACKLOG-10022] - Analyzer osgi

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg
pentaho-karaf-features/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

~~**Do not merge** and see https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/77.~~
Needed by https://github.com/pentaho/marketplace/pull/114.

[BACKLOG-10830] Load marketplace features from descriptors

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml

@CodeOnCoffee, @rmansoor, could you please take a look? Here is PR for common-ui: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/827.

[PPP-3559] - Use of vulnerable component Angular.js 1.2.15 CVE-2015-0167

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

@CodeOnCoffee @krivera-pentaho 
Updating project versions in `custom.properties`

[CLEANUP]Update project version

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

The same than https://github.com/pentaho/pentaho-karaf-assembly/pull/246.
@pamval, @dkincade please check.

[BACKLOG-11939] Change xstream bundle to the one from Apache ServiceMix

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

- Move pdi-marketplace feature from runtimeFeatures to featuresBoot

[SP-2974][BACKLOG-10830] Load marketplace features from descriptors

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

com.thoughtworks.xstream v1.4.2/1.4.7 in karaf bundles
- copied activemq-client feature description

[SP-3005] Backport of PPP-3554 - Use of vulnerable component

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Needed by https://github.com/pentaho/marketplace/pull/125.
@pamval, @graimundo please review.

[SP-2974] Backport of PPP-3559 - Use of vulnerable angular-sanitize 1.2.15

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Related with https://github.com/pentaho/marketplace/pull/126.
@pamval please review.

[6.1][SP-2974][BACKLOG-10830] Remove external angular-translate from marketplace

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Revert: [SP-3005][PPP-3554] Use of vulnerable component com.thoughtworks.xstream v1.4.2/1.4.7 in karaf bundles

Revert: [SP-3005][PPP-3554] Use of vulnerable component com.thoughtworks.xstream v1.4.2/1.4.7 in karaf bundles

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8

[ENGOPS-2639] json GAV change

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pme-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Reverts pentaho/pentaho-karaf-assembly#279

Revert "[PDI-15059] - Updated slf4j jars to 1.7.22 version in karaf"

---

pentaho-osgi-config/pom.xml
pentaho-osgi-config/src/main/resources/pentaho.big.data.impl.cluster.cfg

dialog and make it possible to be use with variables

[BACKLOG-14915]-Dynamically populate storage list box on the cluster

---

pentaho-osgi-config/pom.xml
pentaho-osgi-config/src/main/resources/pentaho.big.data.impl.cluster.cfg

Reverts pentaho/pentaho-karaf-assembly#285

Revert "[BACKLOG-14915]-Dynamically populate storage list box on the cluster"

---

pentaho-karaf-features/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

@lgrill-pentaho @emartin-pentaho 
dependent on https://github.com/pentaho/pdi-monitoring-plugin/pull/70

[ENGOPS-2995] obf fix for monitoring and version prop cleanup

---

pentaho-blueprint-activators/src/main/resources/krb5-jaas.xml
pentaho-osgi-config/pom.xml
pentaho-osgi-config/src/main/resources/pentaho.kerberos.cfg

@pentaho/rogueone 
Please review.

[BACKLOG-15513] Add parameterized krb5-jaas.xml blueprint xml to pentaho-karaf-assembly/pentaho-blueprint-activators

---

pentaho-blueprint-activators/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

@pentaho-nbaker 
@pentaho/rogueone 
Please review.

[BACKLOG-15513] Add pentaho-kerberos-jaas feature to pentaho-client

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.pentaho.pdi.engine.spark.cfg

Also removed SortRows, since there's now a native impl.
@kurtwalker

[BACKLOG-15857]  Added to the forceCoalesceSteps list.

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-carte/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-default/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-kitchen/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-pan/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark-executor/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg

@CodeOnCoffee / @hudak / @mkambol

[BACKLOG-15249] Minimizing the startup of the spark executor

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark/org.pentaho.features.cfg

@mkambol / @hudak / @CodeOnCoffee

[BACKLOG-15249]  Removed uneeded features from etc-spark configuration.

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

@pentaho/rogueone 
@CodeOnCoffee 
Please review.

[BACKLOG-15748] Add marker feature ael-security

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties

Required along with this pull request
https://github.com/pentaho/pentaho-kettle/pull/3752
https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/115
https://github.com/pentaho/pentaho-ee/pull/158

[BACKLOG-15902] Add features for Spark to server

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
pom.xml

@pentaho-nbaker   @lgrill-pentaho

[CLEANUP] Updating to use properties for version

---

pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-pmr/etc-default/org.pentaho.features.cfg

[BACKLOG-15977] PMR handles it's own feature set. Need to ensure that etc-default is empty.

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

@lgrill-pentaho @emartin-pentaho @e-cuellar @ViswesvarSekar

[ENGOPS-3148] groupId change for mavenized kettle plugins

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

Reverts pentaho/pentaho-karaf-assembly#348

Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pom.xml

Reverts pentaho/pentaho-karaf-assembly#353

Revert "[PPP-3807]-Use of vulnerable component camel-blueprint-2.14.3.jar CVE-2017-5643 CVE-2017-3159 CVE-2015-5348 CVE-2015-5344"

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Added jna.jar and jna-platform.jar bundles for big-data-plugin/kettle-plugins/spark.
See this pull request along with https://github.com/pentaho/big-data-plugin/pull/952

[BAD-615]-Spark on Windows: PDI doesn't receive response from Resource Manager when "Blocking" is disabled in Spark submit step

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc/startup.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Includes BACKLOG-17445 - Pentaho Web Package deployer.
Needs https://github.com/pentaho/pentaho-osgi-bundles/pull/228.

[BACKLOG-17443] Pentaho Web Package extender

---

pentaho-karaf-assembly/pom.xml

Needs https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1155.

[BACKLOG-17445] Simplify the exploded config folder

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

- forced using overridden feature descriptors by specifying their exact version in every other descriptor with their usage
- minor changes to remove bundle duplications

[PPP-3850] Enforce resolve order for overridden feature descriptors

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-pme/org.apache.karaf.features.cfg

[BACKLOG-19163] PME (CE) - error to start-up bundle "mvn:org.eclips.jetty.aggregate"

---

pentaho-blueprint-activators/src/main/resources/camel-jms.xml
pentaho-blueprint-activators/src/main/resources/jms-broker.xml
pentaho-blueprint-activators/src/main/resources/jms.xml
pentaho-blueprint-activators/src/main/resources/krb5-jaas.xml
pentaho-blueprint-activators/src/main/resources/monitoring-jms-broker.xml
pentaho-blueprint-activators/src/main/resources/monitoring-jms.xml
pentaho-blueprint-activators/src/main/resources/monitoring-snmp.xml
pentaho-blueprint-activators/src/main/resources/proxy-watcher.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pme-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-client/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-pme/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc/mondrian.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pentaho-osgi-config/src/main/resources/pentaho.jms.cfg
pentaho-osgi-config/src/main/resources/pentaho.kerberos.cfg
pentaho-osgi-config/src/main/resources/pentaho.pdi.monitoring.cfg
pentaho-osgi-config/src/main/resources/pentaho.snmp.cfg

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3544] change Pentaho to Hitachi Vantara and update copyright date

---

pentaho-karaf-assembly/pom.xml

[BACKLOG-19406] - PME throws a karaf exception on start-up (always)

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-carte/org.pentaho.features.cfg

Master PR: https://github.com/pentaho/pentaho-karaf-assembly/pull/389

[BACKLOG-19784] Added run configuration support to carte

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

[PPP-3876]-Use of vulnerable component spring-security-core 4.1.9 cve-2017-4995

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml

@mkambol / @flbrino / @baudekin / @pentaho-jrice

[BACKLOG-19486] Removing dead code

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-1757] version name consolidation

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

@VasilinaTerehova @lgrill-pentaho

[CLEANUP] fix version properties

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-carte/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-default/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-kitchen/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-pan/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-pme/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-pmr/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-prd/org.apache.karaf.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg

@VasilinaTerehova please take a view and merge

Separate shims features, remove shim features from spark karaf start

---

overrides/pom.xml
overrides/src/main/feature/feature.xml
pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pme-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml
pom.xml

@hbfernandes @tmcsantos @pentaho/2-1b please review
@mchen-len-son once this PR is merged please rework the changes of https://github.com/pentaho/pentaho-karaf-assembly/pull/402 using this new way of doing the overrides.

[BACKLOG-20696] - Added mechanism to add bundle overrides in the karaf assembly.

---

pentaho-karaf-assembly/src/main/distribution-server/plugin.xml

[BACKLOG-20623] Added comment explaining the plugin's reason

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

@VasilinaTerehova please take a view and merge

[BACKLOG-20783]-pme prd error with pig impersonation bundle

---

pentaho-blueprint-activators/pom.xml
pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/pom.xml
pentaho-osgi-config/pom.xml
pom.xml

@pentaho/x-wing 
Depends on https://github.com/pentaho/maven-parent-poms/pull/53

[ENGOPS-2977] Update build helper plugin

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml

Master: https://github.com/pentaho/pentaho-karaf-assembly/pull/446
8.1: https://github.com/pentaho/pentaho-karaf-assembly/pull/447
8.1.0.0: https://github.com/pentaho/pentaho-karaf-assembly/pull/448

[BACKLOG-22966] Fixed a issue with monitoring-snmp bundle

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc/startup.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[BACKLOG-21716] Replace inline pentaho-requirejs-osgi-manager feature

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Reverts pentaho/pentaho-karaf-assembly#450

Revert "[PPP-4108] - Use of vulnerable component jackson-databind-2.8.8.jar, …"

---

pentaho-karaf-assembly/src/main/distribution-server/config/web-client/client-config-enabler-require-js-cfg.js

…nd , `pentaho/instanceInfo` to `pentaho/modules`

[BACKLOG-23466] Refactor VizAPI module system: Change pentaho/instanceInfo to pentaho/modules

---

pentaho-karaf-assembly/src/main/distribution-server/config/web-client/client-config-enabler-require-js-cfg.js

@pentaho/millenniumfalcon please merge.
Merge with: pentaho/pentaho-platform-plugin-common-ui#1302.

[BACKLOG-23466] Refactor VizAPI module system.

---

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark-executor/org.pentaho.features.cfg
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spark/org.pentaho.features.cfg

[BACKLOG-23733] Fixing HBase issue on YARN

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties

[CLEANUP] Fixed broken build for Pentaho server

---

pentaho-karaf-assembly/pom.xml

[BACKLOG-26037] Remvoing AEL from CE assembly to EE only assembly

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/org.apache.karaf.features.cfg

@pentaho/millenniumfalcon @etwebdetails please review

[BACKLOG-26380] - Added pdi-data-refinery to karaf featuresBoot

---

pom.xml

This is a series of PRs, please see pentaho/maven-parent-poms#82 for full list.
@ssamora

[PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

---

overrides/pom.xml
pentaho-blueprint-activators/pom.xml
pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/pom.xml
pentaho-osgi-config/pom.xml
pom.xml

[REBASE] Code rebase against master.

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

Reverts pentaho/pentaho-karaf-assembly#510

Revert "PPP-4280:  Changed Karaf feature to use xalan 2.7.2_3"

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

[SP-4861][PPP-4280] Changed Karaf feature to use xalan 2.7.2_3

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pom.xml

[BACKLOG-27569] Centralize pax-web dependency management

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

[BACKLOG-27574] Centralize Felix HTTP dependency version

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/110.
@graimundo please review.

[BACKLOG-27565] Use cxf-jaxrs feature instead of full cxf

---

pentaho-karaf-assembly/pom.xml
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/111
@graimundo

[BACKLOG-27566] Centralize SLF4J dependency

---

pentaho-karaf-assembly/src/main/distribution-server/config/web-client/client-config-enabler-require-js-cfg.js

@pentaho/millenniumfalcon please review
- Needs: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1397

[BACKLOG-27098] Change full AMD module id of pentaho/config/deploy

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml

[PPP-4223] - Fixing property name of karaf springframework

---

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml

@graimundo and @befc please review.

[BACKLOG-27569] i18n feature must declare its dependency on http-whiteboard

---

features/pentaho-karaf-features/pom.xml

@ricardosilva88 @jmcrfp please review

[BACKLOG-27632] - Corrected pentaho-karaf-features parent pom.

---

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties

@pentaho-lmartins @befc please review

[PPP-4271] - Removed extra bracket

---

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

This enables AEL to access HDP's Warehouse Connector Jar.

[BACKLOG-26978] AEL Table Input/Output

---

karaf-assembly/pentaho-karaf-assembly-client/src/main/resources-filtered/etc/org.apache.karaf.features.cfg

[BACKLOG-29565] - PDI-CE Assembly - Fixing features.cfg versions

---

karaf-assembly/pom.xml
pom.xml

@pentaho/millenniumfalcon 
CC: @graimundo

[BACKLOG-29565] - PDI-CE Assembly - Fixing karaf-maven-version override

---

karaf-assembly/pentaho-karaf-assembly-client/src/main/resources-filtered/etc/custom.properties

cc: @Pancho7  
@ccaspanello @baudekin

[BACKLOG-29565] - PDI-CE Assembly - Fixing custom.properties

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

Update to custom.properties to handle dependency for pdi-dataservice plugin. Step moved from engine to plugins/core

[BACKLOG-22188] Decouple constant step from Kettle engine

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties

Reverts pentaho/pentaho-karaf-assembly#561 based on discussion on decoupling steps.

Revert "[BACKLOG-22188] Decouple constant step from Kettle engine"

---

assemblies/client/pom.xml
assemblies/client/src/main/resources-filtered/etc-spoon/org.pentaho.features.cfg

@pentaho/moseisley Please review.

[BACKLOG-30103] - Add the OSGi shims to PDI community edition.

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/common-resources/src/main/resources-filtered/etc/startup.properties
assemblies/pme/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/pmr/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/prd/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

Needs https://github.com/pentaho/pentaho-osgi-bundles/pull/333.
@graimundo please review.

[karaf_update] Use the wrapped version of pax-logging-api

---

features/pentaho-features/pentaho-karaf-features-enterprise/src/main/feature/feature.xml
features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
features/pentaho-features/pentaho-karaf-features-standard/pom.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
pom.xml

Needs https://github.com/pentaho/pentaho-osgi-bundles/pull/338.
@graimundo please review.

[BACKLOG-31352] Move pdi-osgi-bridge-activator to pentaho-base feature

---

assemblies/client/pom.xml
assemblies/client/src/main/resources-filtered/etc-carte/org.pentaho.features.cfg
assemblies/client/src/main/resources-filtered/etc-pan/org.pentaho.features.cfg
assemblies/client/src/main/resources-filtered/etc-spoon/org.pentaho.features.cfg
assemblies/pme/pom.xml
assemblies/pme/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/pmr/pom.xml
assemblies/pmr/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/prd/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
pom.xml

https://jira.pentaho.com/browse/BACKLOG-30640

[BACKLOG-30640] Adding Apache shim to assembly

---

features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[CLEANUP] Remove unneeded dependency on patched org.apache.karaf.features.extension

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/custom.properties
pom.xml

[BACKLOG-32230] Only export packages of Servlet API and not Core JSP API

---

assemblies/server/src/main/resources-filtered/etc/custom.properties
pom.xml

[BACKLOG-32230] Restore export of JSP and JSTL APIs

---

assemblies/server/src/main/resources-filtered/etc/custom.properties

@pentaho/millenniumfalcon please review

[BACKLOG-32957] Karaf logs under pentaho Server are created under pentaho-solutions

---

assemblies/client/src/main/resources/etc-spoon/org.pentaho.features.cfg

@ssamora 
@smmribeiro 
@moraesvc

[PDI-18681] - PDI CE VFS does not show Hadoop Cluster Connections

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

[BACKLOG-35370] Adding jakarta.xml.bind-api to custom.properties; JDK11

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/pmr/src/assembly/assembly.xml
assemblies/prd/src/assembly/assembly.xml
assemblies/server/src/assembly/assembly.xml
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

[BISERVER-14727] Upgrade pax-logging-log4j2 in karaf assembly

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

Sync with master

---

pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pme-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml

[SP-6106] [BISERVER-14787] Removing pax-logging vulnerable components

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

spark/JDK11 update.
This commit is a cherry-pick from master e202602

[BACKLOG-35663] Add missing dependencies and other cleanup after

---

assemblies/client/pom.xml
assemblies/client/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/client/src/main/resources/etc-spoon/org.pentaho.features.cfg
pom.xml

[BACKLOG-35865] Remove references to file-open-save-new plugin from

---

features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[BACKLOG-35890] Remove old metastore and repository locator plugins from

---

assemblies/client/pom.xml
assemblies/client/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/client/src/main/resources/etc-spoon/org.pentaho.features.cfg
pom.xml

migrated from karaf to kettle plugin.

[BACKLOG-35867] Initial check-in of repository connect dialog plugin,

---

features/pentaho-features/pentaho-karaf-features-enterprise/src/main/feature/feature.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[BACKLOG-35831] Remove references to streaming features; no streaming

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/common-resources/src/main/resources-filtered/etc/startup.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
pom.xml

commons-io to use the latest version.

[PPP-4654] Override karaf maven dependencies on older versions of

---

assemblies/client/pom.xml
assemblies/client/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/client/src/main/resources/etc-spoon/org.pentaho.features.cfg
assemblies/server/pom.xml
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
pom.xml

[BACKLOG-36141] JSON step fields dialog moved from karaf; remove all

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

@smmribeiro 
@renato-s 
Upgrading xstream version

[PPP-4704] - Vulnerable Component: xstream-1.4.17

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
pom.xml

[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

Reverts pentaho/pentaho-karaf-assembly#717

Revert "[PPP-4704] - Vulnerable Component: xstream-1.4.17"

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

[PPP-4610] - Use of Vulnerable Component: Components/snakeyaml:1.25

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

@smmribeiro 
@renato-s 
@bcostahitachivantara

[SP-6250] -Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.3 Suite)

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties

[SP-6251] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.4 Suite)

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

@smmribeiro 
@renato-s 
@bcostahitachivantara

[SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

@renato-s 
@smmribeiro 
@bcostahitachivantara

[SP-6305] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.3 Suite)

---

features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
pom.xml

@renato-s 
@smmribeiro 
@bcostahitachivantara

[PPP-4882] - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3

---

features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
pom.xml

Original PR: [https://github.com/pentaho/pentaho-karaf-assembly/pull/735](https://github.com/pentaho/pentaho-karaf-assembly/pull/735)
@smmribeiro 
@renato-s

[SP-6383] - Backport of PPP-4882 - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3 (9.3 Suite)

---

features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
pom.xml

Original PR: [https://github.com/pentaho/pentaho-karaf-assembly/pull/735](https://github.com/pentaho/pentaho-karaf-assembly/pull/735)
@renato-s 
@smmribeiro

[SP-6384] - Backport of PPP-4882 - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3 (9.5 Suite)

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/common-resources/src/main/resources-filtered/etc/startup.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[PPP-4936]-Vulnerable Component -Guava upgraded to 32.1.2-jre version
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4936]-Vulnerable Component -Guava upgraded to 32.1.2-jre version

---

features/pentaho-features/pentaho-karaf-features-enterprise/src/main/feature/feature.xml

[BACKLOG-40283] Need to prevent java.* packages from being added to the

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

@smmribeiro 
@renato-s 
Note this PR includes not only safeyaml but also jackson-dataformat-yaml upgrade

[PPP-4865] - Snakeyaml and Karaf Update - Karaf 4.2.15

---

assemblies/server/src/main/resources-filtered/etc/custom.properties

@smmribeiro 
@renato-s 
Fixing missing or wrongful property name

[PPP-4865] - Snakeyaml and Karaf Update - fixing wrong property name

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

---

features/pentaho-features/pentaho-karaf-features-enterprise/src/main/feature/feature.xml

[PPP-5077]-Vulnerable Component: mina-core
[PPP-5077]: https://hv-eng.atlassian.net/browse/PPP-5077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-5077]-Vulnerable Component: mina-core

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml

Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

---

features/pentaho-features/pentaho-karaf-features-enterprise/src/main/feature/feature.xml

[REVERT] PPP-5077-Vulnerable Component: mina-core

[REVERT] PPP-5077-Vulnerable Component: mina-core

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/custom.properties
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[BACKLOG-41287]-Upgrading pentaho-karaf-assembly features to support with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41287]-Upgrading pentaho-karaf-assembly features to support with Tomcat-10.X

---

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

---

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
assemblies/server/src/main/resources-filtered/etc/custom.properties
features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml
features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
pom.xml

[BACKLOG-43209]-OSGI Assembly issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43209]-OSGI Assembly issues

---

assemblies/client/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/common-resources/src/main/resources-filtered/etc/startup.properties
assemblies/pme/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/pmr/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/prd/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.cfg
pom.xml

Original PR:
- https://github.com/pentaho/pentaho-karaf-assembly/pull/800
@pentaho/tatooine_dev

[SP-6788] Backport of BACKLOG-43212 - Replace Karaf version with HV specific version

---

features/pentaho-features/pentaho-karaf-features-enterprise/pom.xml
features/pentaho-features/pentaho-karaf-features-server/pom.xml
features/pentaho-features/pentaho-karaf-features-standard/pom.xml
overrides/pom.xml

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
