pentaho/pentaho-karaf-assembly

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
[BACKLOG-312] - Adding missing bundles to the pentaho-metaverse-ee feature
=> [BACKLOG-312] - Adding missing bundles to the pentaho-metaverse-ee feature

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
[BACKLOG-1336] - Fixing issues with enunciate being required in the osgi container.
=> [BACKLOG-1336] - Fixing issues with enunciate being required in the osgi container.

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
Pentaho Client is depending on the big data plugin, right now the plugin is not working and this is preventing the server from starting.
=> [CLEANUP] - Commenting out the Big Data dependency

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
Add org.pentaho.di.ui.xul which exports KettleXulLoader class
=> [BACKLOG-4406] Some Data Service windows lost their icon (in the title bar)

pentaho-karaf-assembly/pom.xml
Add missing features.
An attempt has been made to make it as close to kettle-client as it's possible:
only three features were skipped: dataservice, metaverse and marketplace
apparently they are not needed on pmr runtime
@dkincade @brosander
=> [BACKLOG-5216] - PMR libraries staging archive lacks some pentaho karaf features

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties, pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
Prevents linkage errors when di.core components use it in signature
=> [BACKLOG-5857] - Loading log4j from system classloader

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
Waits for the jcrRepository Bean to be created before starting the the Karaf 2 minute timeout in KarafFeatureWatcherImpl
=> [BACKLOG-5858] Introduce ServiceBarrier backed BarrierBeans

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
feature"
This reverts commit a0e0e3560c87d7d8dabc62665480387856b14138.
=> [BACKLOG-6057] Revert "[BACKLOG-5942] - Using cxf version in standard

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
org.pentaho.platform.api.monitoring.snmp into karaf with version 6.1.0
=> [BACKLOG-6866] Exposing package

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
[BACKLOG-9763] - Adding modeler as a dependency of the pdi-dataservice feature
=> [BACKLOG-9763] - Adding modeler as a dependency of the pdi-dataservice feature

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties
fix separate custom.properties for servers in pentaho, this fix actual for bundles that use jersey external libraries as osgi bundle
=> [BACKLOG-9781] - Error launching Pentaho Server EE on bundle pdi-data-refinery

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties, pentaho-karaf-features/src/main/resources/pentaho-karaf-features-server.xml
- Updated the custom.properties to use springframework -
4.3.2.RELEASE and springsecurity 4.1.3.RELEASE
- Updated pentaho-karaf-features-server.xml to remove
pentaho-ss4-proxy, pentaho-ss2-proxy
and upgraded the version of spring framework and
security in pentaho-server feature
=> [BACKLOG-10623] Spring framework and spring security upgrade

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml, pom.xml
@pamval please review. The same than #242 and https://github.com/pentaho/pentaho-karaf-assembly/pull/243.
=> [CHERRY-PICK-7.0-RC][BACKLOG-12099] Adds xstream 1.4.9 needed by data-refinery-pdi-plugin

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml, pom.xml
@pamval please review. The same than https://github.com/pentaho/pentaho-karaf-assembly/pull/242.
=> [CHERRY-PICK-7.0-SP][BACKLOG-12099] Adds xstream 1.4.9 needed by data-refinery-pdi-plugin

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml, pom.xml
@pamval, it's https://github.com/pentaho/pentaho-karaf-assembly/pull/243 to 6.1. Thanks.
=> [BACKLOG-12099] - backport to 6.1

pentaho-karaf-assembly/pom.xml, pom.xml
- eigenbase-xom dependency is updated to 1.3.5
@mbatchelor, @pamval, @lucboudreau, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
Removing legacy ESAPI encoder from projects and replacing it by org.owasp.encoder
=> PDI-15515 - Removing legacy ESAPI encoder from projects

pentaho-karaf-assembly/pom.xml, pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml, pom.xml
Related with https://github.com/pentaho/marketplace/pull/127.
@pamval please review.
=> [6.1.0.9][SP-2974][BACKLOG-10830] Remove external angular-translate from marketplace

pentaho-karaf-features/pom.xml, pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml
@pentaho/millenniumfalcon @nantunes please review
Removing manually defined feature for pentaho geo as the feature is now automatically handled by the geo plugin. Geo is now included in PDI through DET.
Related PRs:
https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/96
https://github.com/pentaho/pentaho-det-ee/pull/360
https://github.com/pentaho/pentaho-platform-plugin-geo/pull/137
This reverts commit a3cecef2ded7eaa34b626c7de0bcf08582b173e7.
=> Revert "[BACKLOG-13473] -- added pentaho-geo feature"

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
**org.apache.commons.beanutils** is not required to be imported in **custom.properties** file, each project that requires this dependency should call it
=> [BACKLOG-15780] Remove commmons-beanutils from custom.properties

pentaho-blueprint-activators/src/main/resources/krb5-jaas.xml
@pentaho/rogueone Please review.
Change debug flag to false so that debug message won't show up in console.
=> [CLEANUP] Disable unnecessary debug message output in jaas:config

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
@CodeOnCoffee add packages needed for UserGroupInformation class.  
Belongs with other PR: https://github.com/pentaho/pentaho-ee/pull/157
=> [BACKLOG-15171] AEL proxy-user. For UserGroupInformation class.

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-spoon/org.pentaho.features.cfg
@pentaho/rogueone Remove ael-security from karaf-assembly so jaas won't be enabled by default. Please review.
=> [CLEANUP] remove ael-security feature from karaf-assembly

pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml
- Client-extras add addition etc folder for cart, kitchen, pan and spark. This is not needed in PRD
=> [BACKLOG-16246] - Remove client-extras from karaf prd assembly

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
Exporting 2 packages more through OSGi's system bundle. 
OSGi platform EE plugins that require these should not be forced to bundle them into its own feature as these 2 already exist. They merely need to be exposed to the OSGi world via our system bundle.
@pentaho/rogueone @pentaho/rebelalliance
=> [BACKLOG-17323] Create a worker-nodes-ee OSGi plugin

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
To allow FileSystem to be used by SparkOperations in AEL.
=> [BACKLOG-19243] Adding org.apache.hadoop.fs to custom.properties

pentaho-karaf-assembly/src/main/filtered-resources/client-extras/etc-scale/org.pentaho.features.cfg
- living alongside `etc-carte`, `etc-pan`, `etc-kitchen`, ... folders, there will now be an `etc-scale`
@pentaho/rogueone please review
=> [BACKLOG-21649] adding etc-scale folder to karaf client assembly

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-enterprise.xml, pom.xml
This fixes the NoClassDefFoundError: com/ibm/icu/text/DateFormat posted in qat-builds channel
@pentaho/millenniumfalcon @bennychow please review
=> [BACKLOG-21720] - Adding icu4j to the pentaho-analyzer feature

pentaho-karaf-assembly/src/main/descriptors/pentaho-client-assembly.xml, pentaho-karaf-assembly/src/main/descriptors/pentaho-pme-assembly.xml, pentaho-karaf-assembly/src/main/descriptors/pentaho-pmr-assembly.xml, pentaho-karaf-assembly/src/main/descriptors/pentaho-prd-assembly.xml, pentaho-karaf-assembly/src/main/descriptors/pentaho-server-assembly.xml
Remove exclusion of activemq-osgi/5.10.0 karaf overrides has a bug that requires overriden bundles to be present to load the manifest to inspect bundle information.
Not having the overriden bundle was preventing activemq bundles , features from installing
Testing: The 5.10.0 activemq-osgi bundle gets shipped with the ee-karaf-assembly. Verified that the zip has both versions. Unzipped system/org/apache/activemq of ee version and restarted server and made sure that pentaho-camel-jms and activemq features are installed and no exception is thrown in pentaho.log 
Merge along with related PR :  https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/190
Note: Make sure any verification testing is done on a system that does not have maven installed
@pentaho/rogueone @graimundo
=> BACKLOG-21582 : Remove exclusion of activemq-osgi/5.10.0 

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
Reverts pentaho/pentaho-karaf-assembly#395
- Reverted as per the decisions made ( and captured ) at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=336291#comment-336291
Part of a bulk-revert, comprised of the PR list captured at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593:
@pentaho/rogueone @pamval @dkincade @mbatchelor @mdamour1976 @graimundo 
~Please **hold off merging** until we have triggered a "Revert PR" for all PRs outlined in https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593~ ✅ 
* https://github.com/pentaho/pentaho-engineering-samples/pull/61
* https://github.com/pentaho/marketplace/pull/147
* https://github.com/pentaho/data-access/pull/999
* https://github.com/pentaho/pentaho-kettle/pull/5176
* …
=> Revert "[PPP-3876]-Use of vulnerable component spring-security-core 4.1.9 cve-2017-4995"

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
Reverts pentaho/pentaho-karaf-assembly#437
@pentaho/rogueone @pamval @dkincade @mbatchelor @mdamour1976 @graimundo
**List or PRs**
- https://github.com/pentaho/marketplace/pull/149
- https://github.com/pentaho/pentaho-metadata-editor-ee/pull/37
- https://github.com/pentaho/pentaho-metadata-editor/pull/124
- https://github.com/pentaho/pentaho-kettle/pull/5275
- https://github.com/pentaho/pentaho-platform/pull/4111
- https://github.com/pentaho/pentaho-platform-ee/pull/1266
- https://github.com/pentaho/pentaho-karaf-assembly/pull/441
- https://github.com/pentaho/pdi-ee-plugin/pull/357
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/107
- https://github.com/pentaho/pentaho-reporting/pull/1134
- https://github.com/pentaho/pentaho-osgi-bundles/pull/265
=> Revert "[BACKLOG-22526] vulnerable component spring-security: upgrade from 4.…"

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
- `ETL Metadata injection` was converted from its OSGi from, to the "classic" PDI plugin form
To be merged alongside https://github.com/pentaho/pentaho-kettle/pull/5693 
@pentaho/rogueone @kurtwalker @mdamour1976 @hbfernandes @tmcsantos please process
=> [BACKLOG-25015] Meta-inject - Move step to Kettle plugin system

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
@pentaho/millenniumfalcon please review. @jgminder I just cherry-picked your proposed fix.
=> [BACKLOG-24699] Fix Spoon CE start up error of missing pentaho-requirejs-osgi-manager

pentaho-karaf-assembly/src/main/filtered-resources/etc-server/custom.properties, pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
This is one of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

pentaho-osgi-config/src/main/resources/pentaho.metaverse.cfg
This is a harmless typo and not a showstopper, since this property assumes the default value of true, but should be fixed
=> [BACKLOG-26820] Fixing a typo in the pentaho.metaverse.cfg file

pentaho-karaf-features/src/main/resources/pentaho-karaf-features-standard.xml
This change was to resolve a security vulnerability in xalan 2.7.1_7
=> PPP-4280:  Changed Karaf feature to use xalan 2.7.2_3 

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
These are needed to load vendor specific classes for Spark Impala support on AEL
=> [BACKLOG-27420] adds cloudera impala packages for Spark JDBC

pentaho-karaf-assembly/src/main/filtered-resources/etc/custom.properties
This is required to access the locally install Hive connection jars we are required to use.
=> [BACKLOG-27708] Table Input/Output for Hive HDP 2.6 - installation issue

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, assemblies/server/src/main/resources-filtered/etc/custom.properties
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Updating karaf assembly version for commons-vfs2
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/102
- https://github.com/pentaho/pdi-plugins-ee/pull/139
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/82
- …
=> [PDI-17775] Process Files step no longer supports HTTP scheme

features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
Reverts change in https://github.com/pentaho/pentaho-karaf-assembly/commit/9fe63898dff7da1b5fae7982a21cef7b2fa099ef#diff-ca79bb24347de45717db44dd8a90b0efR235 which is causing the build to fail with the error:
`Unable to build assembly: Could not find matching feature for pentaho-jackson/1.0`
Related to: https://github.com/pentaho/maven-parent-poms/pull/201
@graimundo please review and merge.
=> [PPP-4461] Reverting change to 'pentaho-jackson' version

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, assemblies/server/src/main/resources-filtered/etc/custom.properties
This reverts commit 98d765768a13421d657061858aa2bb26fcd47408, reversing
changes made to 6cb7bf40f0c12667a2aac10b2e5973b8b8808641.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #634 from gryphendowre/SP-5370"

pentaho-osgi-config/src/main/resources/pentaho.metaverse.cfg
- add property "lineage.external.resource.cache.expire.time" to pentaho.metaverse.cfg
=> [PDI-18657] Memory leak when customer executes jobs on the server

assemblies/server/src/main/resources-filtered/etc/custom.properties, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
- Adding com.hitachivantara.security.web.api.* packages to server custom.properties
- Add CSRF client dependency to pdi data refinery feature
Previous code review PR: https://github.com/pentaho/pentaho-karaf-assembly/pull/651.
Part of the changeset described in https://github.com/pentaho/security-web/pull/4#issuecomment-888511840.
=> [BACKLOG-35000] Adding com.hitachivantara.security.web packages to custom.properties

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml, assemblies/common-resources/src/main/resources-filtered/etc/startup.properties, assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
Assure that we use HV pax-logging wraps (pax-logging-api-wrap and pax-logging-log4j2-wrap).
@rmansoor
=> [SP-6107] Upgrade log4j2 (use HV pax-logging wraps)

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml, assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
bundle; it should only come from the main classpath.
=> [BACKLOG-35743] Ensure slf4j-api library is not pulled into karaf as a

features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml, pentaho-osgi-config/pom.xml
to a kettle plugin.  metaverse-web still exists.
=> [BACKLOG-36184] Remove references to metaverse-core; this has been moved

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml, assemblies/server/src/main/resources-filtered/etc/custom.properties, assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
for karaf ssh service (and presumably anything else in karaf reliant on them).  Standardizing on the jdk15to18 packages since these still work on JDK1.8 (they are not multiversion jars).
=> [BACKLOG-37531] Bouncycastle release/version mismatch causing problems

assemblies/common-resources/src/main/resources-filtered/etc/startup.properties, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
[BACKLOG-39435] OSGI is not able to load Guava bundle after upgradation.
[BACKLOG-39435]: https://hv-eng.atlassian.net/browse/BACKLOG-39435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-39435] OSGI is not able to load Guava bundle after upgradation.

assemblies/common-resources/src/main/resources/etc/config.properties, assemblies/common-resources/src/main/resources/etc/jre.properties
These were copied from karaf 4.3.3 which explicitly supports JDK17. Unknown if these updates plus additional --add-opens are all we will need to keep the existing karaf version working with JDK17, but this is a start.
=> [BACKLOG-39584] Changes required to get karaf to start under JDK17.

assemblies/server/src/main/resources-filtered/etc/custom.properties
[BACKLOG-41381]-Pentaho Server CE throwing wiring errors on boot
[BACKLOG-41381]: https://hv-eng.atlassian.net/browse/BACKLOG-41381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41381]-Pentaho Server CE throwing wiring errors on boot

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, assemblies/server/src/main/resources-filtered/etc/custom.properties
(cherry picked from commit 4c88c6b40cbab94e013131e30232dd36ac1f5c4c) Backport of [BACKLOG-41390] - Adding the package where PermissionDeniedException exists
@pentaho/tatooine_dev 
[BACKLOG-41390]: https://hv-eng.atlassian.net/browse/BACKLOG-41390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SP-6624] Backport of PDI-20219 - Charts do not function in DET in 9.3.0.8 (9.3 Suite)

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml, assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
[BACKLOG-42817]-Upgrading fasterxml jaxrs to fasterxml jakarta rs to support with jersey 3.x and jakarta 3.x
[BACKLOG-42817]: https://hv-eng.atlassian.net/browse/BACKLOG-42817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42817]-Upgrading fasterxml jaxrs to fasterxml jakarta rs to support with jersey 3.x and jakarta 3.x

assemblies/common-resources/src/main/resources-filtered/etc/org.apache.karaf.features.xml, assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
[BACKLOG-42955]-Upgrading jackson-module-jaxb-annotations to jackson-module-jakarta-xmlbind-annotations to support Jakarta EE
[BACKLOG-42955]: https://hv-eng.atlassian.net/browse/BACKLOG-42955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-42955]-Upgrading jackson-module-jaxb-annotations to jackson-module-jakarta-xmlbind-annotations to support Jakarta EE

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties
=> [PPP-5447] - Vulnerable Component: XStream 1.4.20

assemblies/server/src/main/resources-filtered/etc/org.apache.karaf.features.xml
Actual PR: https://github.com/pentaho/pentaho-karaf-assembly/pull/797
=> [SP-6749] Backport of PPP-5480 - Upgrade "pax-web" to address Vulnerable Component: Tomcat 9.0.91 (10.2 Suite)

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml
[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43209]-OSGi Assembly Issues

assemblies/common-resources/src/main/resources-filtered/etc/custom.properties, assemblies/common-resources/src/main/resources/etc/jre.properties, assemblies/server/src/main/resources-filtered/etc/custom.properties, features/pentaho-features/pentaho-karaf-features-server/src/main/feature/feature.xml, features/pentaho-features/pentaho-karaf-features-standard/src/main/feature/feature.xml, pom.xml
This pull request introduces significant updates to dependencies and system package configurations, primarily focused on transitioning from older `javax` packages to newer `jakarta` packages and modernizing the dependency versions. It also removes outdated libraries and adds new ones to align with the latest standards and frameworks.
* [`assemblies/common-resources/src/main/resources-filtered/etc/custom.properties`](diffhunk://#diff-c769f5b439d68e42360931ce7fc9a68cc7a7e44e1af6d2020fe781a8a9e908d0L68-R80): Replaced `javax.annotation`, `javax.xml.bind`, and `javax.servlet` with their `jakarta` equivalents, including `jakarta.annotation`, `jakarta.xml.bind`, and `jakarta.servlet`. Added new `jakarta.ws.rs` and `jakarta.inject` packages for enhanced support.
* …
=> [BACKLOG-40823] - Upgrade the Tomcat version from current to 10.x.x with Java 17

features/pentaho-features/pentaho-karaf-features-enterprise/pom.xml, features/pentaho-features/pentaho-karaf-features-server/pom.xml, features/pentaho-features/pentaho-karaf-features-standard/pom.xml, overrides/pom.xml
When using JDK 21, Maven enforces stricter validation on packaging types. If a module is configured with the packaging type feature (commonly used in Eclipse/Tycho-based builds), Maven fails with an error similar to:
"The packaging plugin for project  “**** " did not assign a main file to the project but it has attachments. Change packaging to 'pom'."
This occurs because feature is not a standard packaging type recognized by core Maven plugins. As a result, Maven is unable to process the module unless special handling is applied.
To minimize disruption while preserving product integrity, the identified solution is to configure:
`<allowIncompleteProjects>true</allowIncompleteProjects>`
within the maven-install-plugin and maven-deploy-plugin only for modules with packaging type feature. …
=> [BACKLOG-43902]-Java 21 : compatibility check for Pentaho and fix Build and Run time issues while building / testing
